### ISSUE TITLE
GPL-nnn Simplify purpose.yml configuration

### ISSUE THREAD

**Issue by JamesGlover** [sanger/limber#541]
**User story**
Each purpose configuration option largely exists in a fairly flat structure. This can make it difficult to see how options relate. I propose refactoring this.

***Stage 1***
Re-organize the yaml structure itself to group keys under their relevant sections. Eg.

This:
```
Example plate:
  :stock_plate: true
  :cherrypickable_target: true
  :input_plate: true
  :asset_type: plate
  :presenter_class: Presenters::PcrPresenter
  :creator_class: LabwareCreators::TaggedPlate
  warnings:
    pcr_cycles_not_in:
      - 6
  :tag_layout_templates:
  - TS_pWGSA_UDI96
  - TS_pWGSB_UDI96
  - TS_pWGSC_UDI96
  - TS_pWGSD_UDI96
```

Into this:
```
Example plate:
  asset_type: plate
  registration_options:
    stock_plate: true
    cherrypickable_target: true
    input_plate: true
  presenter:
    class: Presenters::PcrPresenter
    options:
      warnings:
        pcr_cycles_not_in:
        - 6
  creator:
    class: LabwareCreators::TaggedPlate
    options:
      tag_layout_templates:
      - TS_pWGSA_UDI96
      - TS_pWGSB_UDI96
      - TS_pWGSC_UDI96
      - TS_pWGSD_UDI96
  shared:
    options: {}
```

Shared options can be passed into both presenters/and creators.

*** Stage 2 ***

- Refactor configuration loading to be passed in to creators/presenters rather having presenters/creators looking up the config
- Furthermore, if each presenter/creator has its configuration handled by a config object we have a good place to put
  config specific documentation, and even validation.

**Who are the primary contacts for this story**
e.g. John S (don't include surnames in public repos)

**Acceptance criteria**
To be considered successful the solution must allow:
- [ ] add a list of acceptance criteria here
- [ ] ...

**Dependencies**
This story is blocked by the following dependencies:
- #<issue_no.>
- sanger/<repo>#<issue_no.>

**Additional context**
