### ISSUE TITLE
DPL-067-6 Tag clash issue research

### ISSUE THREAD

**Issue by KatyTaylor** [sanger/limber#844]
**User story**
As a developer I want to validate our approach for resolving the Cardinal tag clash issue before continuing with the rest of the stories.

**Who are the primary contacts for this story**
Katy, Harry, Eduardo

**Acceptance criteria**
Create data with the following structure:
- [x] Go along the Cardinal pipeline as normal until you reach the LCA PBMC plate
- [x] Create the next plate (LCA PBMC Pools), linking to the LCA PBMC in the normal way
- [x] In the LCA PBMC plate, create new 'compound' samples (there won't be a link between them yet - in the future there would be the new sample links table).
- [x] Progress down the rest of the pipeline as normal, check there are no errors when viewing each plate, in Limber or in Sequencescape.
- [ ] Try pooling the final tubes using 'poolings/new' (in Sequencescape)
- [ ] Try making a sequencing submission and batch, and progressing it through the sequencing pipeline.

**References**
This story is research for https://github.com/sanger/limber/issues/759

**Comment by harrietc52** [comment]
Learning
- We updated all wells on the Pool Plate to have empty samples, this doesn't also remove the transfer request
- The created _pseudo_ sample, has to have a transfer requests, for samples to appear in following (even though the transfer request is on a well? .. which didn't change ...)

**Comment by emrojo** [comment]
List of changes to make it work with Submissions:

1)	In pipelines/high_throughput_cardinal, split in 2 pipelines: Cardinal Library Aggretation and Cardinal Library Prep.

```yaml
Cardinal Library Aggregation:
  filters:
    request_type_key: limber_cardinal
    # TODO: DPL-061 library_type: Cardinal   do we need to specify library type here when starting on blood tubes?
  relationships:
    LCA Blood Array: LCA PBMC
    LCA PBMC: LCA PBMC Pools

Cardinal Library Prep: # Cardinal Library preparation pipeline
  filters: &cardinal_filters
    request_type_key: limber_cardinal
    # TODO: DPL-061 library_type: Cardinal   do we need to specify library type here when starting on blood tubes?
  library_pass: LCA Connect PCRXP
  relationships:
    LCA PBMC Pools: LCA 10X cDNA
    LCA 10X cDNA: LCA Connect PCRXP
    LCA Connect PCRXP: LCA Custom Pool
    LCA Custom Pool: LCA Custom Pool Norm
```
 I think we should use a different request type for the Library aggregation pipeline, but for the moment for testing it could work this way.

2)	Change purposes.yml the plate purpose LCA PBMC Pools:

```yaml
LCA PBMC Pools:
  :asset_type: plate
  :stock_plate: true
  :cherrypickable_target: false
  :input_plate: true
  # TODO: DPL-064 is this presenter suitable or do we need something special that displays parent tube details?
  :presenter_class: Presenters::StockPlatePresenter
```

3)	In Sequencescape console add support for using the plate purpose LCA PBMC Pools to use the RequestType ‘limber_cardinal’:
```ruby
RequestType::RequestTypePlatePurpose.create(request_type: RequestType.find_by_key('limber_cardinal'), plate_purpose: PlatePurpose.find_by(name: 'LCA PBMC Pools'))
```

Then to manually run this workflow in UAT you need to set up a plate and create a submission:
1)	In Sequencescape, Go to ‘UAT Actions’ / ‘Generate plate’ and create 1 plate of purpose ‘LCA PBMC Pools’, with 8 wells.
2)	In Sequencescape, Go to ‘A study’ / ‘Create submission’ 
a.	Select template ‘Limber – Cardinal’
b.	Write some values (Fragmen size from 100 to 100, library type ‘Cardinal’, PCR Cycles 100)
c.	Click ‘Add order’
d.	Select study ‘A study; and project ‘A project’
e.	Click on tab ‘From Plate and Wells’
i.	Write the barcode in the box
ii.	Click on ‘Save order’

After this you should be able to scan this plate an process it in Limber.

To implement these changes to happen automatically in the workflow:
-	LabwareCreators::CardinalPoolsPlate should call SS API and:
o	 create ‘LCA PBMC Pools’ plate with the new 8 aggregated samples (using a v2 endpoint for create plate)
o	create the submission using the template ‘Limber – Cardinal’ (I think is in v1, there should be an example of this in Limber already)
